### ISSUE TITLE
API changes for File module

### ISSUE THREAD

**Issue by tormozz48** [enb-make/enb-source-map#9]
Now enb-source-map has some strange and unsuitable API

I and @blond have some proposals to change:
* method `render` of `File` module should return object instead of string. This object should have fields:
`contents` - content of file, and `map` - source map object (without complex wrappers)
* method `joinContentAndSourceMap` if 'Utils' module should be able to take source map as simple Object (instead of instance of `SourceMapGenerator` class)
* Also `render` method should have option which will paste inlined source map into code

**Comment by tormozz48** [comment]
* Also `render` method should have option which will paste inlined source map into code

**Comment by j0tunn** [comment]
> method joinContentAndSourceMap if 'Utils' module should be able to take source map as simple Object (instead of instance of SourceMapGenerator class)

why?
Do you want to make it public API?
